# Generated by Django 4.2.5 on 2023-09-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmed',
            field=models.BooleanField(default=False, help_text='Email Confirmation Status', verbose_name='Подтверждение почты'),
        ),
    ]
