# Generated by Django 4.2.5 on 2023-09-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_confirmemailtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='external_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='Внешний ИД'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
