# Generated by Django 4.2.5 on 2023-10-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_cart_products_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('shop', 'Магазин'), ('buyer', 'Покупатель')], max_length=10, verbose_name='Тип пользователя'),
        ),
    ]
