# Generated by Django 4.2.5 on 2023-09-29 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_parameter_options_remove_cart_created_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_product', to='backend.productinfo', verbose_name='Информация о продукте'),
        ),
    ]
