# Generated by Django 4.2.5 on 2023-09-29 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_cartitem_product_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='backend.cartitem', verbose_name='Корзина'),
        ),
    ]
