# Generated by Django 4.2.5 on 2023-10-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products_info',
            field=models.ManyToManyField(related_name='products_info', through='backend.CartItem', to='backend.productinfo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('assebled', 'Собран'), ('sent', 'Отправлен'), ('delivered', 'Доставлен'), ('canceled', 'Отменен')], max_length=20, verbose_name='Статус'),
        ),
    ]
