# Generated by Django 4.2.5 on 2023-09-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='external_id',
            field=models.PositiveIntegerField(blank=True, unique=True, verbose_name='Внешний ИД'),
        ),
    ]
